package:
  name: svtoolbox
  version: 'v1.0'

source:
  git_rev: v1.0
  git_url: git@github.com:micknudsen/svtoolbox.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - click
    - pysam
    - python >=3.10

about:
  home: https://github.com/micknudsen/svtoolbox
