package:
  name: mantatools
  version: '0.1.1'

source:
  git_rev: v0.1.1
  git_url: git@github.com:micknudsen/mantatools.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - click
    - pysam
    - python >=3.9

about:
  home: https://github.com/micknudsen/mantatools
